// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app_settings.sql

package repository

import (
	"context"
)

const getAppSettings = `-- name: GetAppSettings :one
SELECT id, week_start_day, history_weeks, created_at, updated_at
FROM app_settings
WHERE id = 1
`

func (q *Queries) GetAppSettings(ctx context.Context) (AppSetting, error) {
	row := q.db.QueryRowContext(ctx, getAppSettings)
	var i AppSetting
	err := row.Scan(
		&i.ID,
		&i.WeekStartDay,
		&i.HistoryWeeks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAppSettings = `-- name: UpsertAppSettings :exec
INSERT INTO app_settings (id, week_start_day, history_weeks)
VALUES (1, ?, ?)
ON DUPLICATE KEY UPDATE week_start_day = VALUES(week_start_day), history_weeks = VALUES(history_weeks)
`

type UpsertAppSettingsParams struct {
	WeekStartDay int8 `json:"week_start_day"`
	HistoryWeeks int8 `json:"history_weeks"`
}

func (q *Queries) UpsertAppSettings(ctx context.Context, arg UpsertAppSettingsParams) error {
	_, err := q.db.ExecContext(ctx, upsertAppSettings, arg.WeekStartDay, arg.HistoryWeeks)
	return err
}
