// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menses_periods.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createMensesPeriod = `-- name: CreateMensesPeriod :execlastid
INSERT INTO menses_periods (user_id, start_date, end_date) VALUES (?, ?, ?)
`

type CreateMensesPeriodParams struct {
	UserID    int64        `json:"user_id"`
	StartDate time.Time    `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

func (q *Queries) CreateMensesPeriod(ctx context.Context, arg CreateMensesPeriodParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createMensesPeriod, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteMensesPeriod = `-- name: DeleteMensesPeriod :exec
DELETE FROM menses_periods WHERE id = ? AND user_id = ?
`

type DeleteMensesPeriodParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteMensesPeriod(ctx context.Context, arg DeleteMensesPeriodParams) error {
	_, err := q.db.ExecContext(ctx, deleteMensesPeriod, arg.ID, arg.UserID)
	return err
}

const getMensesPeriod = `-- name: GetMensesPeriod :one
SELECT id, user_id, start_date, end_date, created_at, updated_at
FROM menses_periods WHERE id = ? AND user_id = ?
`

type GetMensesPeriodParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetMensesPeriod(ctx context.Context, arg GetMensesPeriodParams) (MensesPeriod, error) {
	row := q.db.QueryRowContext(ctx, getMensesPeriod, arg.ID, arg.UserID)
	var i MensesPeriod
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMensesPeriodsForUser = `-- name: ListMensesPeriodsForUser :many
SELECT id, user_id, start_date, end_date, created_at, updated_at
FROM menses_periods WHERE user_id = ? ORDER BY start_date DESC
`

func (q *Queries) ListMensesPeriodsForUser(ctx context.Context, userID int64) ([]MensesPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listMensesPeriodsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MensesPeriod{}
	for rows.Next() {
		var i MensesPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMensesPeriodsForUserInRange = `-- name: ListMensesPeriodsForUserInRange :many
SELECT id, user_id, start_date, end_date, created_at, updated_at
FROM menses_periods
WHERE user_id = ?
  AND start_date <= ?
  AND (end_date IS NULL OR end_date >= ?)
ORDER BY start_date ASC
`

type ListMensesPeriodsForUserInRangeParams struct {
	UserID   int64        `json:"user_id"`
	ToDate   time.Time    `json:"to_date"`
	FromDate sql.NullTime `json:"from_date"`
}

func (q *Queries) ListMensesPeriodsForUserInRange(ctx context.Context, arg ListMensesPeriodsForUserInRangeParams) ([]MensesPeriod, error) {
	rows, err := q.db.QueryContext(ctx, listMensesPeriodsForUserInRange, arg.UserID, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MensesPeriod{}
	for rows.Next() {
		var i MensesPeriod
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMensesPeriod = `-- name: UpdateMensesPeriod :exec
UPDATE menses_periods SET start_date = ?, end_date = ? WHERE id = ? AND user_id = ?
`

type UpdateMensesPeriodParams struct {
	StartDate time.Time    `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
}

func (q *Queries) UpdateMensesPeriod(ctx context.Context, arg UpdateMensesPeriodParams) error {
	_, err := q.db.ExecContext(ctx, updateMensesPeriod,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
		arg.UserID,
	)
	return err
}
