// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type TasksFrequency string

const (
	TasksFrequencyDaily   TasksFrequency = "daily"
	TasksFrequencyWeekly  TasksFrequency = "weekly"
	TasksFrequencyMonthly TasksFrequency = "monthly"
	TasksFrequencyYearly  TasksFrequency = "yearly"
)

func (e *TasksFrequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TasksFrequency(s)
	case string:
		*e = TasksFrequency(s)
	default:
		return fmt.Errorf("unsupported scan type for TasksFrequency: %T", src)
	}
	return nil
}

type NullTasksFrequency struct {
	TasksFrequency TasksFrequency `json:"tasks_frequency"`
	Valid          bool           `json:"valid"` // Valid is true if TasksFrequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTasksFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.TasksFrequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TasksFrequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTasksFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TasksFrequency), nil
}

type UsersRole string

const (
	UsersRoleAdmin UsersRole = "admin"
	UsersRoleUser  UsersRole = "user"
)

func (e *UsersRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UsersRole(s)
	case string:
		*e = UsersRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UsersRole: %T", src)
	}
	return nil
}

type NullUsersRole struct {
	UsersRole UsersRole `json:"users_role"`
	Valid     bool      `json:"valid"` // Valid is true if UsersRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUsersRole) Scan(value interface{}) error {
	if value == nil {
		ns.UsersRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UsersRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUsersRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UsersRole), nil
}

type MensesPeriod struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	StartDate time.Time    `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Task struct {
	ID                 int64          `json:"id"`
	Title              string         `json:"title"`
	Frequency          TasksFrequency `json:"frequency"`
	StartDate          time.Time      `json:"start_date"`
	EndDate            sql.NullTime   `json:"end_date"`
	Active             bool           `json:"active"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	Sequence           int32          `json:"sequence"`
	Description        sql.NullString `json:"description"`
	ExemptDuringMenses bool           `json:"exempt_during_menses"`
}

type TaskCompletion struct {
	ID          int64     `json:"id"`
	TaskID      int64     `json:"task_id"`
	UserID      int64     `json:"user_id"`
	DueDate     time.Time `json:"due_date"`
	CompletedAt time.Time `json:"completed_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Name         string    `json:"name"`
	Role         UsersRole `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
