// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset_tokens.sql

package repository

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token_hash, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreatePasswordResetTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.ExecContext(ctx, createPasswordResetToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at <= CURRENT_TIMESTAMP OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const getValidPasswordResetToken = `-- name: GetValidPasswordResetToken :one
SELECT token_hash, user_id, expires_at, used_at, created_at
FROM password_reset_tokens
WHERE token_hash = ? AND used_at IS NULL AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRowContext(ctx, getValidPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :execrows
UPDATE password_reset_tokens
SET used_at = CURRENT_TIMESTAMP
WHERE token_hash = ? AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markPasswordResetTokenUsed, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
