// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package repository

import (
	"context"
	"database/sql"
	"time"
)

const createTask = `-- name: CreateTask :execlastid
INSERT INTO tasks (title, description, category, frequency, start_date, end_date, active)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Frequency   TasksFrequency `json:"frequency"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Active      bool           `json:"active"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, category, frequency, start_date, end_date, active, created_at, updated_at
FROM tasks
WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT id, title, description, category, frequency, start_date, end_date, active, created_at, updated_at
FROM tasks
WHERE active = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListActiveTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskCategories = `-- name: ListTaskCategories :many
SELECT DISTINCT category
FROM tasks
WHERE category IS NOT NULL AND category <> ''
ORDER BY category ASC
`

func (q *Queries) ListTaskCategories(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listTaskCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, category, frequency, start_date, end_date, active, created_at, updated_at
FROM tasks
ORDER BY created_at DESC
`

func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTaskActive = `-- name: SetTaskActive :exec
UPDATE tasks SET active = ? WHERE id = ?
`

type SetTaskActiveParams struct {
	Active bool  `json:"active"`
	ID     int64 `json:"id"`
}

func (q *Queries) SetTaskActive(ctx context.Context, arg SetTaskActiveParams) error {
	_, err := q.db.ExecContext(ctx, setTaskActive, arg.Active, arg.ID)
	return err
}

const updateTask = `-- name: UpdateTask :exec
UPDATE tasks
SET title = ?, description = ?, category = ?, frequency = ?, start_date = ?, end_date = ?, active = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
	Frequency   TasksFrequency `json:"frequency"`
	StartDate   time.Time      `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	Active      bool           `json:"active"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) error {
	_, err := q.db.ExecContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Frequency,
		arg.StartDate,
		arg.EndDate,
		arg.Active,
		arg.ID,
	)
	return err
}
