// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_completions.sql

package repository

import (
	"context"
	"strings"
	"time"
)

const deleteCompletionsForUserOnDates = `-- name: DeleteCompletionsForUserOnDates :exec
DELETE FROM task_completions
WHERE user_id = ? AND due_date IN (/*SLICE:due_dates*/?)
`

type DeleteCompletionsForUserOnDatesParams struct {
	UserID   int64       `json:"user_id"`
	DueDates []time.Time `json:"due_dates"`
}

func (q *Queries) DeleteCompletionsForUserOnDates(ctx context.Context, arg DeleteCompletionsForUserOnDatesParams) error {
	query := deleteCompletionsForUserOnDates
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.DueDates) > 0 {
		for _, v := range arg.DueDates {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:due_dates*/?", strings.Repeat(",?", len(arg.DueDates))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:due_dates*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const getCompletion = `-- name: GetCompletion :one
SELECT id, task_id, user_id, due_date, completed_at, created_at
FROM task_completions
WHERE task_id = ? AND user_id = ? AND due_date = ?
`

type GetCompletionParams struct {
	TaskID  int64     `json:"task_id"`
	UserID  int64     `json:"user_id"`
	DueDate time.Time `json:"due_date"`
}

func (q *Queries) GetCompletion(ctx context.Context, arg GetCompletionParams) (TaskCompletion, error) {
	row := q.db.QueryRowContext(ctx, getCompletion, arg.TaskID, arg.UserID, arg.DueDate)
	var i TaskCompletion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.DueDate,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCompletionsForUserInRange = `-- name: ListCompletionsForUserInRange :many
SELECT id, task_id, user_id, due_date, completed_at, created_at
FROM task_completions
WHERE user_id = ? AND due_date BETWEEN ? AND ?
ORDER BY due_date ASC
`

type ListCompletionsForUserInRangeParams struct {
	UserID      int64     `json:"user_id"`
	FromDueDate time.Time `json:"from_due_date"`
	ToDueDate   time.Time `json:"to_due_date"`
}

func (q *Queries) ListCompletionsForUserInRange(ctx context.Context, arg ListCompletionsForUserInRangeParams) ([]TaskCompletion, error) {
	rows, err := q.db.QueryContext(ctx, listCompletionsForUserInRange, arg.UserID, arg.FromDueDate, arg.ToDueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskCompletion{}
	for rows.Next() {
		var i TaskCompletion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionsForUserOnDate = `-- name: ListCompletionsForUserOnDate :many
SELECT id, task_id, user_id, due_date, completed_at, created_at
FROM task_completions
WHERE user_id = ? AND due_date = ?
`

type ListCompletionsForUserOnDateParams struct {
	UserID  int64     `json:"user_id"`
	DueDate time.Time `json:"due_date"`
}

func (q *Queries) ListCompletionsForUserOnDate(ctx context.Context, arg ListCompletionsForUserOnDateParams) ([]TaskCompletion, error) {
	rows, err := q.db.QueryContext(ctx, listCompletionsForUserOnDate, arg.UserID, arg.DueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskCompletion{}
	for rows.Next() {
		var i TaskCompletion
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.DueDate,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskComplete = `-- name: MarkTaskComplete :exec
INSERT INTO task_completions (task_id, user_id, due_date, completed_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE completed_at = CURRENT_TIMESTAMP
`

type MarkTaskCompleteParams struct {
	TaskID  int64     `json:"task_id"`
	UserID  int64     `json:"user_id"`
	DueDate time.Time `json:"due_date"`
}

func (q *Queries) MarkTaskComplete(ctx context.Context, arg MarkTaskCompleteParams) error {
	_, err := q.db.ExecContext(ctx, markTaskComplete, arg.TaskID, arg.UserID, arg.DueDate)
	return err
}

const markTaskIncomplete = `-- name: MarkTaskIncomplete :exec
DELETE FROM task_completions
WHERE task_id = ? AND user_id = ? AND due_date = ?
`

type MarkTaskIncompleteParams struct {
	TaskID  int64     `json:"task_id"`
	UserID  int64     `json:"user_id"`
	DueDate time.Time `json:"due_date"`
}

func (q *Queries) MarkTaskIncomplete(ctx context.Context, arg MarkTaskIncompleteParams) error {
	_, err := q.db.ExecContext(ctx, markTaskIncomplete, arg.TaskID, arg.UserID, arg.DueDate)
	return err
}
